-- 为spaces表添加icon字段支持
-- 这个脚本会添加icon字段并设置默认值

-- 添加icon字段
ALTER TABLE spaces ADD COLUMN IF NOT EXISTS icon TEXT DEFAULT '📦';

-- 更新现有数据的图标
UPDATE spaces 
SET icon = CASE 
  WHEN level = 1 THEN 
    CASE name
      WHEN '客厅' THEN '🛋️'
      WHEN '卧室' THEN '🛏️'
      WHEN '厨房' THEN '🍳'
      WHEN '卫生间' THEN '🚿'
      WHEN '书房' THEN '📚'
      WHEN '阳台' THEN '🌱'
      WHEN '储物间' THEN '📦'
      WHEN '衣帽间' THEN '👔'
      WHEN '餐厅' THEN '🍽️'
      WHEN '儿童房' THEN '🧸'
      WHEN '老人房' THEN '👴'
      WHEN '客房' THEN '🛌'
      WHEN '健身房' THEN '💪'
      WHEN '影音室' THEN '🎬'
      WHEN '游戏室' THEN '🎮'
      WHEN '工作间' THEN '💼'
      WHEN '洗衣房' THEN '🧺'
      WHEN '车库' THEN '🚗'
      WHEN '花园' THEN '🌺'
      WHEN '露台' THEN '☀️'
      ELSE '🏠'
    END
  WHEN level = 2 THEN 
    CASE name
      WHEN '沙发' THEN '🛋️'
      WHEN '茶几' THEN '☕'
      WHEN '电视柜' THEN '📺'
      WHEN '书架' THEN '📚'
      WHEN '衣柜' THEN '👕'
      WHEN '床头柜' THEN '🛏️'
      WHEN '梳妆台' THEN '💄'
      WHEN '床' THEN '🛏️'
      WHEN '餐桌' THEN '🍽️'
      WHEN '餐椅' THEN '🪑'
      WHEN '书桌' THEN '📝'
      WHEN '办公椅' THEN '🪑'
      WHEN '文件柜' THEN '📁'
      WHEN '置物架' THEN '📦'
      WHEN '鞋柜' THEN '👠'
      WHEN '首饰盒' THEN '💍'
      WHEN '工具箱' THEN '🔧'
      WHEN '行李箱' THEN '🧳'
      WHEN '花架' THEN '🌱'
      WHEN '晾衣架' THEN '👕'
      WHEN '毛巾架' THEN '🧺'
      WHEN '浴室柜' THEN '🧴'
      WHEN '马桶柜' THEN '🧻'
      WHEN '冰箱' THEN '❄️'
      WHEN '微波炉' THEN '🔥'
      WHEN '洗碗机' THEN '🍽️'
      WHEN '洗衣机' THEN '🧺'
      WHEN '烘干机' THEN '🌞'
      WHEN '电视' THEN '📺'
      WHEN '音响' THEN '🔊'
      WHEN '电脑' THEN '💻'
      WHEN '打印机' THEN '🖨️'
      WHEN '空调' THEN '❄️'
      WHEN '电风扇' THEN '💨'
      WHEN '电热水器' THEN '🚿'
      WHEN '电饭煲' THEN '🍚'
      WHEN '电磁炉' THEN '🔥'
      WHEN '烤箱' THEN '🍞'
      WHEN '豆浆机' THEN '🥛'
      WHEN '榨汁机' THEN '🍊'
      WHEN '咖啡机' THEN '☕'
      WHEN '电水壶' THEN '🫖'
      WHEN '电熨斗' THEN '👔'
      WHEN '吸尘器' THEN '🧹'
      WHEN '扫地机器人' THEN '🤖'
      WHEN '橱柜' THEN '🥘'
      WHEN '抽屉' THEN '📥'
      WHEN '储物盒' THEN '📦'
      WHEN '收纳袋' THEN '👜'
      WHEN '挂钩' THEN '🪝'
      WHEN '置物篮' THEN '🧺'
      WHEN '药箱' THEN '💊'
      WHEN '文具盒' THEN '✏️'
      WHEN '钱包' THEN '👛'
      WHEN '钥匙扣' THEN '🔑'
      WHEN '雨伞架' THEN '☔'
      WHEN '鞋架' THEN '👠'
      WHEN '衣架' THEN '👕'
      WHEN '书立' THEN '📚'
      WHEN '文件夹' THEN '📁'
      WHEN '相框' THEN '🖼️'
      WHEN '花瓶' THEN '🌺'
      WHEN '垃圾桶' THEN '🗑️'
      WHEN '回收箱' THEN '♻️'
      WHEN '床底' THEN '🛏️'
      WHEN '天花板' THEN '🏠'
      WHEN '地板' THEN '🟫'
      WHEN '墙壁' THEN '🧱'
      WHEN '门后' THEN '🚪'
      WHEN '窗台' THEN '🪟'
      WHEN '角落' THEN '📐'
      WHEN '过道' THEN '🚶'
      WHEN '楼梯' THEN '🪜'
      WHEN '电梯' THEN '🛗'
      WHEN '地下室' THEN '🏚️'
      WHEN '阁楼' THEN '🏠'
      WHEN '花园' THEN '🌺'
      WHEN '露台' THEN '☀️'
      WHEN '游泳池' THEN '🏊'
      WHEN '烧烤架' THEN '🔥'
      WHEN '秋千' THEN '🪑'
      WHEN '沙坑' THEN '🏖️'
      WHEN '篮球架' THEN '🏀'
      WHEN '网球场' THEN '🎾'
      WHEN '停车场' THEN '🅿️'
      WHEN '垃圾箱' THEN '🗑️'
      WHEN '邮箱' THEN '📮'
      WHEN '门铃' THEN '🔔'
      WHEN '监控' THEN '📹'
      WHEN '报警器' THEN '🚨'
      WHEN '灭火器' THEN '🧯'
      WHEN '急救箱' THEN '🏥'
      WHEN '保险箱' THEN '🔒'
      WHEN '保险柜' THEN '🏦'
      WHEN '金库' THEN '💰'
      WHEN '密室' THEN '🚪'
      WHEN '暗道' THEN '🕳️'
      WHEN '地窖' THEN '🏚️'
      WHEN '酒窖' THEN '🍷'
      WHEN '雪茄房' THEN '🚬'
      WHEN '游戏室' THEN '🎮'
      WHEN '影音室' THEN '🎬'
      WHEN '健身房' THEN '💪'
      WHEN '桑拿房' THEN '🧖'
      WHEN '按摩椅' THEN '💆'
      WHEN '瑜伽室' THEN '🧘'
      WHEN '冥想室' THEN '🧘‍♀️'
      WHEN '祈祷室' THEN '🙏'
      WHEN '书房' THEN '📚'
      WHEN '画室' THEN '🎨'
      WHEN '音乐室' THEN '🎵'
      WHEN '舞蹈室' THEN '💃'
      WHEN '摄影棚' THEN '📸'
      WHEN '录音棚' THEN '🎤'
      WHEN '工作室' THEN '💼'
      WHEN '会议室' THEN '🤝'
      WHEN '接待室' THEN '👋'
      WHEN '休息室' THEN '☕'
      WHEN '吸烟室' THEN '🚬'
      WHEN '母婴室' THEN '👶'
      WHEN '无障碍' THEN '♿'
      WHEN '紧急出口' THEN '🚪'
      WHEN '消防通道' THEN '🚒'
      WHEN '避难所' THEN '🏠'
      ELSE '📦'
    END
  ELSE '📦'
END
WHERE icon IS NULL OR icon = '📦';

-- 创建索引以提高查询性能
CREATE INDEX IF NOT EXISTS idx_spaces_icon ON spaces(icon); 